#!/bin/bash
#Variables
OS_RC=deployRC
#OP_CONTROLLER=192.168.1.37
OP_CONTROLLER=cmartinez.no-ip.biz
SSHCON="ssh -i deployerkey deployer@$OP_CONTROLLER"
SSHCONFIG=`find /etc/ -name ssh_config |tail -1`
f_root(){
  user=$(whoami)
  if [ $user == root ]; then
    echo -e "Conprovació de privilegis correcta"
  else
    echo -e "[*] Error - Necessita permissos de root."
    exit 1
fi
}
f_sshConfig(){
# Funció per validar la configuració ssh per poder enviar variables d'entorn per ssh
    grep "^SendEnv OS_AUTH_URL OS_TENANT_ID OS_TENANT_NAME OS_USERNAME OS_PASSWORD" $SSHCONFIG > /dev/null
    if [ $? -eq 0 ];
    then
      echo -e "- Parametros de traspaso de variables\t\t [OK]"
    else
      echo SendEnv OS_AUTH_URL OS_TENANT_ID OS_TENANT_NAME OS_USERNAME OS_PASSWORD >> $SSHCONFIG
    fi
}
f_sshClearConfig(){
  sed -i"bkp" '/SendEnv OS_AUTH_URL OS_TENANT_ID OS_TENANT_NAME OS_USERNAME OS_PASSWORD/d' $SSHCONFIG
}
f_getInstanceInfo(){
  #echo TO-DO
  $SSHCON -C "nova show $INSTANCENAME"
  QUERY="select uuid from instances where vm_state like \"active\" and display_name like \"$INSTANCENAME\";"
  QUERY2=$(echo "\"select uuid from nova.instances where vm_state like 'active' and display_name like '$INSTANCENAME';\"|mysql -udeployer| tail -1")
  UUID=`$SSHCON -C "echo $QUERY2"`
  IP=`$SSHCON -C "nova floating-ip-bulk-list | grep $UUID | cut -d'|' -f3"`
}
f_root
f_sshConfig
source $OS_RC
$SSHCON -C "nova --os-username $OS_USERNAME --os-password $OS_PASSWORD --os-tenant-name $OS_TENANT_NAME list" > /dev/null
if [ $? -eq 0 ];
then
  echo -e "- Verificació de credencials\t\t [OK]"
  INSTANCENAME=ws$OS_USERNAME
else
  echo -e "- Verificació de credencials\t\t [NOK]"
  exit 1
fi
#credencials verificades, creem instancia
#$SSHCON -C "nova boot --image wsGeneral --flavor m1.tiny --key-name $OS_USERNAME ws$OS_USERNAME" > /dev/null
if [ $? -eq 0 ];
then
  echo -e "- Creació d'instancia\t\t [OK]"
else
  echo -e "- Creació d'instancia\t\t [NOK]"
  exit 1
fi
# Obtenim info de la nova instancia
f_getInstanceInfo
#un cop creada la instancia, ja no es necessari connectar amb el node controller.Es fa neteja per seguretat
f_sshClearConfig
#echo "instance $INSTANCENAME $UUID ip: $IP"
echo -n "Introduint una entrada dns al fitxer hosts per $OS_USERNAME.dev.cloud.com"
sed -i"hosbkp" '/$OS_USERNAME.dev.cloud.com/d' /etc/hosts
echo $IP $OS_USERNAME.dev.cloud.com >> /etc/hosts 
if [ $? -eq 0 ];
then
  echo -e "\t\t\t[OK]"
else
  echo -e "\t\t\t[NOK]"
  exit 1
fi
./provision -i $IP -u $OS_USERNAME
exit 0
