#!/bin/bash
##
# Workstation provisioner
# Date:23/05/2013 
# Author: Cristian Martínez
##

# Parameters:
# -u user : Mandatory, it's necessary for copy ssh keys into the new instance
# -p password : Mandatory, password for auth in openstack project
#
f_help(){
   echo "./provision_workstation.sh -u user -p <password> "
   echo "password            Password"
   echo "user                Nom d'usuari"
   echo "-h                  Mostra aquest missatge."
   echo ""
}
# Variables:
USER=""
PASSWORD=""
RCKEYSTONE=/datos/keys/deployer
FLAVOR="m1.tiny"

#
#
#
f_login(){
  source $RCKEYSTONE
}
f_crearInstancia(){
  f_login
  nova boot --flavor m1.tiny --image wsGeneral --key-name host-local ws_$username
}
f_validaParams(){
  if( "$USER" == "" )
  then
    echo "Falta parametre usuari."  
    f_help
    exit
  fi
  if( "$PASSWORD" == "" )
  then
    echo "Falta parametre password."
    f_help
    exit
  fi
}
while test -n "$1"; do
    case "$1" in
        -h)
            f_help
            exit;
            ;;
        -u)
            USER=$2
            shift
            ;;
        -p)
            PASSWORD=$2
            shift
            ;;
         *)
            MESSAGE="Unknown argument: $1"
            f_help
            ;;
        esac
    shift
done
f_validaParams
