#!/bin/bash
##
# Workstation provisioner
# Date:23/05/2013 
# Author: Cristian Martínez
##

# Parameters:
# -u user : Mandatory, it's necessary for copy ssh keys into the new instance
# -p password : Mandatory, password for auth in openstack project
#
f_help(){
   echo "./provision -i IP -u user"
   echo "-h                  Mostra aquest missatge."
   echo ""
}

while test -n "$1"; do
    case "$1" in
        -h)
            f_help
            exit;
            ;;
        -i)
            IP=$2
            shift
            ;;
        -u)
	   USER=$2
	   shift
	   ;; 
	 *)
            MESSAGE="Unknown argument: $1"
            f_help
            ;;
        esac
    shift
done
if [ -z $IP ];
then
  exit 1
fi
echo $USER
SSHDEV="ssh root@$IP"
$SSHDEV -C "useradd -s /bin/bash $USER;"
$SSHDEV -C "mkdir /home/$USER/.ssh;cp -a .ssh/authorized_keys /home/$USER/.ssh/authorized_keys;chown -R $USER: /home/$USER/"
